update module integration test script

diff --git a/tests/test-modules-integration b/tests/test-modules-integration
--- a/tests/test-modules-integration
+++ b/tests/test-modules-integration
@@ -5,11 +5,39 @@ set -o pipefail
 
 SCRIPT_DIRECTORY=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-# shellcheck disable=1091
-source "$SCRIPT_DIRECTORY/constants.sh"
+# Docker settings
+export BORG_PODMAN_NETWORK="borg-ansible-modules"
 
-# Uncomment whenever modules are added
-#tox -e integration -- \
-#    --docker --color -v \
-#    --controller docker:default \
-#    --target "docker:default,python=$PYTHON_VERSION"
+# Cleanup function to delete any docker objects that we might have created
+cleanup() {
+    echo "Cleaning up..."
+    set +e # cleanup, we don't care if some stuff doesn't exist
+    podman network rm "$BORG_PODMAN_NETWORK" > /dev/null
+    echo "Done"
+    set -e
+    exit
+}
+trap cleanup INT ERR EXIT
+
+prepare() {
+    podman network create $BORG_PODMAN_NETWORK
+}
+
+run() {
+    tox -e integration -- \
+        --color -v \
+        --controller docker:default --target "docker:default,python=$PYTHON_VERSION" \
+        --docker-network $BORG_PODMAN_NETWORK  \
+        --docker-terminate=always `#Change this if you want to debug test targets`
+}
+
+main() {
+    # shellcheck disable=1091
+    source "$SCRIPT_DIRECTORY/constants.sh"
+
+    prepare
+    run
+    cleanup
+}
+
+main "$@"
